---
- name: Update and upgrade apt repositories
  hosts: MYHOSTS # replace with actual host file name

  tasks:
   - name: Update and upgrade
     become: true
     ansible.builtin.apt:
      upgrade: true
      update_cache: true
